import XCTest
@testable import AgentHUDCore

final class ChatTranscriptTests: XCTestCase {
    private var directory: URL!

    override func setUpWithError() throws {
        directory = FileManager.default.temporaryDirectory.appendingPathComponent("chat-transcript-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
    }

    override func tearDownWithError() throws { try FileManager.default.removeItem(at: directory) }

    private func json(_ value: [String: Any]) -> String {
        String(decoding: try! JSONSerialization.data(withJSONObject: value), as: UTF8.self)
    }

    private func claudeUser(_ text: String, meta: Bool = false) -> String {
        var o: [String: Any] = ["type": "user", "uuid": UUID().uuidString, "timestamp": "2026-10-08T16:34:36.355Z",
                                "message": ["role": "user", "content": text]]
        if meta { o["isMeta"] = true }
        return json(o)
    }

    private func claudeAssistant(id: String, _ blocks: [[String: Any]]) -> String {
        json(["type": "assistant", "uuid": UUID().uuidString, "timestamp": "2026-10-08T16:34:37.383Z",
              "message": ["id": id, "role": "assistant", "content": blocks]])
    }

    private func codex(_ type: String, _ payload: [String: Any]) -> String {
        json(["type": type, "timestamp": "2026-10-08T16:38:44.265Z", "payload": payload])
    }

    func testClaudeMessagesToolsAndInterrupts() {
        let t = ChatTranscript(path: "/dev/null", agent: .claude)
        t.ingest(lines: [
            claudeUser("<command-name>/clear</command-name>"),
            claudeUser("Caveat: the messages below were generated by the user"),
            claudeUser("hidden", meta: true),
            claudeUser("Fix the duplicate callers"),
            claudeAssistant(id: "m1", [["type": "text", "text": "Looking at the dedupe."]]),
            claudeAssistant(id: "m1", [["type": "tool_use", "id": "tu1", "name": "Read",
                                        "input": ["file_path": "/repo/src/compareCallers.ts"]]]),
            json(["type": "user", "uuid": "r1", "message": ["role": "user",
                  "content": [["type": "tool_result", "tool_use_id": "tu1", "content": "file body"]]]]),
            claudeAssistant(id: "m2", [["type": "tool_use", "id": "tu2", "name": "Bash", "input": ["command": "pnpm test callers"]]]),
            claudeAssistant(id: "m3", [["type": "text", "text": "Keyed on file and range now."]]),
            claudeUser("[Request interrupted by user]"),
        ])
        XCTAssertEqual(t.items.map(\.kind), [.user, .assistant, .tool, .tool, .assistant, .interrupted])
        XCTAssertEqual(t.items[0].text, "Fix the duplicate callers")
        XCTAssertEqual(t.items[2].text, "Read")
        XCTAssertEqual(t.items[2].detail, "compareCallers.ts")
        XCTAssertEqual(t.items[3].detail, "pnpm test callers")
        XCTAssertNotNil(t.items[0].at)
    }

    func testEditorContextIsStrippedFromPrompts() {
        XCTAssertEqual(ChatTranscript.strippingContext("<ide_opened_file>a.md</ide_opened_file>go build it"), "go build it")
        XCTAssertTrue(ChatTranscript.isHarnessText("<external_codex_apps_open_page>{}</external_codex_apps_open_page>"))
        XCTAssertFalse(ChatTranscript.isHarnessText("<b>bold</b> is not a wrapper"))
    }

    func testClaudeMergesTextBlocksOfOneMessage() {
        let t = ChatTranscript(path: "/dev/null", agent: .claude)
        t.ingest(lines: [
            claudeAssistant(id: "m1", [["type": "text", "text": "First part."]]),
            claudeAssistant(id: "m1", [["type": "text", "text": "Second part."]]),
        ])
        XCTAssertEqual(t.items.count, 1)
        XCTAssertEqual(t.items[0].text, "First part.\nSecond part.")
    }

    func testCodexSkipsInjectedContextAndReadsTools() {
        let t = ChatTranscript(path: "/dev/null", agent: .codex)
        t.ingest(lines: [
            codex("response_item", ["type": "message", "role": "developer", "content": [["type": "input_text", "text": "<skills_instructions>"]]]),
            codex("response_item", ["type": "message", "role": "user", "id": "u0",
                                    "content": [["type": "input_text", "text": "<environment_context>\n<cwd>/x</cwd>"]]]),
            codex("response_item", ["type": "message", "role": "user", "id": "u1",
                                    "content": [["type": "input_text", "text": "Export the estimate as a PDF"]]]),
            codex("response_item", ["type": "reasoning", "id": "r1", "summary": []]),
            codex("response_item", ["type": "function_call", "name": "shell", "call_id": "c1",
                                    "arguments": #"{"command":["bash","-lc","pnpm test estimate"]}"#]),
            codex("response_item", ["type": "custom_tool_call", "name": "apply_patch", "call_id": "c2",
                                    "input": "*** Begin Patch\n*** Update File: app/api/route.ts\n@@\n*** End Patch"]),
            codex("response_item", ["type": "message", "role": "assistant", "id": "a1",
                                    "content": [["type": "output_text", "text": "Added the route."]]]),
            codex("event_msg", ["type": "turn_aborted", "turn_id": "t1", "reason": "interrupted"]),
        ])
        XCTAssertEqual(t.items.map(\.kind), [.user, .tool, .tool, .assistant, .interrupted])
        XCTAssertEqual(t.items[1].detail, "bash -lc pnpm test estimate")
        XCTAssertEqual(t.items[2].detail, "route.ts")
    }

    func testReadsOnlyWhatWasAppended() throws {
        let file = directory.appendingPathComponent("t.jsonl")
        try (claudeUser("one") + "\n").write(to: file, atomically: true, encoding: .utf8)
        let t = ChatTranscript(path: file.path, agent: .claude)
        XCTAssertTrue(t.update())
        XCTAssertEqual(t.items.map(\.text), ["one"])
        XCTAssertFalse(t.update())

        // A line written in two pieces only counts once it's finished.
        let line = claudeUser("two")
        let handle = try FileHandle(forWritingTo: file)
        try handle.seekToEnd()
        try handle.write(contentsOf: Data(line.prefix(20).utf8))
        XCTAssertFalse(t.update())
        try handle.write(contentsOf: Data((line.dropFirst(20) + "\n").utf8))
        try handle.close()
        XCTAssertTrue(t.update())
        XCTAssertEqual(t.items.map(\.text), ["one", "two"])

        // Rewritten shorter: start over.
        try (claudeUser("fresh") + "\n").write(to: file, atomically: true, encoding: .utf8)
        t.update()
        XCTAssertEqual(t.items.map(\.text), ["fresh"])
    }

    func testFirstReadStartsNearTheEnd() throws {
        let file = directory.appendingPathComponent("big.jsonl")
        let lines = (1...200).map { claudeUser("message \($0)") }
        try (lines.joined(separator: "\n") + "\n").write(to: file, atomically: true, encoding: .utf8)
        let t = ChatTranscript(path: file.path, agent: .claude, initialBytes: 2000, limit: 5)
        t.update()
        XCTAssertTrue(t.truncated)
        XCTAssertEqual(t.items.count, 5)
        XCTAssertEqual(t.items.last?.text, "message 200")
        XCTAssertEqual(t.items.first?.text, "message 196")
    }

    func testObservedSessionsCanOnlyBeRead() {
        XCTAssertTrue(SessionCapabilities.observed.observe)
        XCTAssertFalse(SessionCapabilities.observed.canSend)
        XCTAssertTrue(SessionCapabilities(sendAtCompletion: true).canSend)
        XCTAssertEqual(SessionControl.observed.mode, .observed)
    }
}
